### PR TITLE
Update OSX binaries

### PR DESCRIPTION
**Pull request by RobertCristian**
This should fix macos Catalina issues

Optipng v0.7.7 - https://optipng.sourceforge.io
Jpegtran v9c - https://www.ijg.org/

### CODE REVIEW

**Comment by emrekutlu** [comment]
Hi @RobertCristian, thank you for the PR.
I tested this on my machine (Mojave 10.14.6) and it fails. 
I don't have Catalina so I cannot test it. 
Did you only test on Catalina?

**Comment by RobertCristian** [comment]
Good point, I will test also on mojave and report back.

**Comment by RobertCristian** [comment]
Hello @emrekutlu, tests are passing on mojave(10.14.6) and Catalina(10.15.1). Both are real machines. Below is a screenshot of the test that i've ran multiple times.

Screenshot 2019-12-06 at 11 16 32

Hopefully I am testing this right 😄

**Comment by emrekutlu** [comment]
Sorry @RobertCristian, I was not clear enough. I did not mean the specs. I tested it on a rails project.

**Comment by RobertCristian** [comment]
Oh, yes...I am using it on an older project that uses rails 5.1.6 with ruby 2.6.5 and works great on both catalina and mojave, compressing and uploading pictures. 

I guess it would be great if someone else could test this and confirm.

**Comment by emrekutlu** [comment]
@RobertCristian I don't want to break anything. So do you mind to update your PR to include jpegtran binary separately, for example adding under `bin/osx/catalina/` and update the [command_path](https://github.com/emrekutlu/paperclip-compression/blob/d96f5349eb58003d3af256b9ced451eacd714b44/lib/paperclip-compression/base.rb#L50) method to run it only for catalina and above.

To detect the operating system version you can use `OS.host_os`, it returns a string like `darwin17.7.0`. Based on the "Release history" section of this [wikipedia article](https://en.wikipedia.org/wiki/Darwin_(operating_system)), darwin 19.0.0 and later versions corresponds to Catalina. 

There is still a caveat about this approach. `OS` uses `rbconfig` to detect operating system properties and they are decided when ruby is compiled. So if you installed ruby on Mojave and upgrade to Catalina, it still shows old data from Mojave. By the way every gem I have come across uses `rbconfig`.

And I made some changes on tests, it would be good if you rebase.
If you don't have time please let me know, I will try to do it myself. I just don't want to steal your commit :)

**Comment by RobertCristian** [comment]
Sorry for late response but I can't do it until after middle of january. If you have time and want to do it, you can do it no problem from me!

**Comment by emrekutlu** [comment]
Binaries are included in the new version (`1.1.0`) with other PR. Thank you @RobertCristian.

**Pull request closed without merging**
